call clean.cmd

clang++ -c -x c++ -O0 -DWIN32 -DNDEBUG -D_WINDOWS -DFT2_BUILD_LIBRARY ^
-I.\include -I.\freetype\include -I.\freetype\include\freetype ^
.\freetype\src\autofit\autofit.c ^
.\freetype\src\bdf\bdf.c ^
.\freetype\src\cff\cff.c ^
.\freetype\src\base\ftbase.c ^
.\freetype\src\base\ftbitmap.c ^
.\freetype\src\cache\ftcache.c ^
.\freetype\src\base\ftfstype.c ^
.\freetype\src\base\ftgasp.c ^
.\freetype\src\base\ftglyph.c ^
.\freetype\src\gzip\ftgzip.c ^
.\freetype\src\base\ftinit.c ^
.\freetype\src\lzw\ftlzw.c ^
.\freetype\src\base\ftstroke.c ^
.\freetype\src\base\ftsystem.c ^
.\freetype\src\smooth\smooth.c ^
.\freetype\src\base\ftbbox.c ^
.\freetype\src\base\ftbdf.c ^
.\freetype\src\base\ftcid.c ^
.\freetype\src\base\ftgxval.c ^
.\freetype\src\base\ftmm.c ^
.\freetype\src\base\ftotval.c ^
.\freetype\src\base\ftpatent.c ^
.\freetype\src\base\ftpfr.c ^
.\freetype\src\base\ftsynth.c ^
.\freetype\src\base\fttype1.c ^
.\freetype\src\base\ftdebug.c ^
.\freetype\src\base\ftwinfnt.c ^
.\freetype\src\pcf\pcf.c ^
.\freetype\src\pfr\pfr.c ^
.\freetype\src\psaux\psaux.c ^
.\freetype\src\pshinter\pshinter.c ^
.\freetype\src\psnames\psmodule.c ^
.\freetype\src\raster\raster.c ^
.\freetype\src\sfnt\sfnt.c ^
.\freetype\src\truetype\truetype.c ^
.\freetype\src\type1\type1.c ^
.\freetype\src\cid\type1cid.c ^
.\freetype\src\type42\type42.c ^
.\freetype\src\winfonts\winfnt.c ^
.\src\hardware\timer.cpp ^
.\src\hardware\vga.cpp ^
.\src\hardware\vga_attr.cpp ^
.\src\hardware\vga_crtc.cpp ^
.\src\hardware\vga_dac.cpp ^
.\src\hardware\vga_gfx.cpp ^
.\src\hardware\vga_memory.cpp ^
.\src\hardware\vga_misc.cpp ^
.\src\hardware\vga_seq.cpp ^
.\src\ints\bios.cpp ^
.\src\ints\bios_keyboard.cpp ^
.\src\cpu\callback.cpp ^
.\src\cpu\core_normal.cpp ^
.\src\cpu\cpu.cpp ^
.\src\dos\devicePRT.cpp ^
.\src\dos\dos.cpp ^
.\src\dos\dos_classes.cpp ^
.\src\dos\dos_devices.cpp ^
.\src\dos\dos_execute.cpp ^
.\src\dos\dos_files.cpp ^
.\src\dos\dos_ioctl.cpp ^
.\src\dos\dos_memory.cpp ^
.\src\dos\dos_misc.cpp ^
.\src\dos\dos_tables.cpp ^
.\src\dos\drives.cpp ^
.\src\ints\ems.cpp ^
.\src\gui\events.cpp ^
.\src\dos\fcb_files.cpp ^
.\src\cpu\flags.cpp ^
.\src\gui\freetype.cpp ^
.\src\gui\gui.cpp ^
.\src\ints\int10.cpp ^
.\src\ints\int10_char.cpp ^
.\src\ints\int10_memory.cpp ^
.\src\ints\int10_modes.cpp ^
.\src\ints\int10_pal.cpp ^
.\src\ints\int10_put_pixel.cpp ^
.\src\ints\int10_vptable.cpp ^
.\src\hardware\iohandler.cpp ^
.\src\hardware\keyboard.cpp ^
.\src\hardware\memory.cpp ^
.\src\ints\mouse.cpp ^
.\src\cpu\paging.cpp ^
.\src\hardware\parport.cpp ^
.\src\hardware\pic.cpp ^
.\src\hardware\serialport.cpp ^
.\src\shell\shell.cpp ^
.\src\misc\support.cpp ^
.\src\gui\video.cpp ^
.\src\ints\xms.cpp ^
.\src\vDos.cpp

windres ./src/winres.rc winres.o

clang++ -v -o vDosPlus-clang-fast.exe *.o -lkernel32 -luser32 -lgdi32 -lshell32 -lshlwapi
