// c
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdio.h>
#include <ctype.h>
#include <process.h>
#include <math.h>
#include <io.h>
#include <time.h>
#include <direct.h>
#include <fcntl.h>
#include <sys/stat.h>
// c++
#include <string>
#include <vector>
#include <map>
#include <cctype>
#include <algorithm>
// windows
#include <windows.h>
#include <mmsystem.h>
#include <shellapi.h>
#include <shlwapi.h>
